name: Cypress parallel Tests

on: 
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: RUN
        run: |
          npm run cy:run:parallel
          npm run cy:run_v2:parallel

